-- Agri Bandhu Cloud MySQL Database Dump
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `cache`;
CREATE TABLE `cache` (
  `key` varchar(255) NOT NULL,
  `value` mediumtext NOT NULL,
  `expiration` int(11) NOT NULL,
  PRIMARY KEY (`key`),
  KEY `cache_expiration_index` (`expiration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `cache` (`key`, `value`, `expiration`) VALUES ('agri_otp_apurv3383@gmail.com', 's:6:\"667047\";', '1785405265');
INSERT INTO `cache` (`key`, `value`, `expiration`) VALUES ('agri_otp_apurvgoel@gmail.com', 's:6:\"353816\";', '1785405250');
INSERT INTO `cache` (`key`, `value`, `expiration`) VALUES ('agri_otp_apurvgoel87@gmail.com', 's:6:\"734994\";', '1785403480');
INSERT INTO `cache` (`key`, `value`, `expiration`) VALUES ('agri_otp_cloud_speed_fixed@agribandhu.in', 's:6:\"641579\";', '1785404603');
INSERT INTO `cache` (`key`, `value`, `expiration`) VALUES ('agri_otp_otp_test_live@agribandhu.in', 's:6:\"540992\";', '1785402843');
INSERT INTO `cache` (`key`, `value`, `expiration`) VALUES ('agri_otp_ramesh_test@agribandhu.in', 's:6:\"822833\";', '1785402347');
INSERT INTO `cache` (`key`, `value`, `expiration`) VALUES ('agri_otp_speed_test_fixed@agribandhu.in', 's:6:\"543748\";', '1785404595');

DROP TABLE IF EXISTS `cache_locks`;
CREATE TABLE `cache_locks` (
  `key` varchar(255) NOT NULL,
  `owner` varchar(255) NOT NULL,
  `expiration` int(11) NOT NULL,
  PRIMARY KEY (`key`),
  KEY `cache_locks_expiration_index` (`expiration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) NOT NULL,
  `connection` text NOT NULL,
  `queue` text NOT NULL,
  `payload` longtext NOT NULL,
  `exception` longtext NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


DROP TABLE IF EXISTS `job_batches`;
CREATE TABLE `job_batches` (
  `id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `total_jobs` int(11) NOT NULL,
  `pending_jobs` int(11) NOT NULL,
  `failed_jobs` int(11) NOT NULL,
  `failed_job_ids` longtext NOT NULL,
  `options` mediumtext DEFAULT NULL,
  `cancelled_at` int(11) DEFAULT NULL,
  `created_at` int(11) NOT NULL,
  `finished_at` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


DROP TABLE IF EXISTS `jobs`;
CREATE TABLE `jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `queue` varchar(255) NOT NULL,
  `payload` longtext NOT NULL,
  `attempts` tinyint(3) unsigned NOT NULL,
  `reserved_at` int(10) unsigned DEFAULT NULL,
  `available_at` int(10) unsigned NOT NULL,
  `created_at` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `jobs_queue_index` (`queue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('1', '0001_01_01_000000_create_users_table', '1');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('2', '0001_01_01_000001_create_cache_table', '1');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('3', '0001_01_01_000002_create_jobs_table', '1');
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES ('4', '2026_07_29_000001_create_scans_table', '2');

DROP TABLE IF EXISTS `password_reset_tokens`;
CREATE TABLE `password_reset_tokens` (
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


DROP TABLE IF EXISTS `scans`;
CREATE TABLE `scans` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `user_name` varchar(255) NOT NULL DEFAULT 'Guest Farmer',
  `crop` varchar(255) NOT NULL,
  `disease_name` varchar(255) NOT NULL,
  `scientific_name` varchar(255) DEFAULT NULL,
  `confidence` double NOT NULL DEFAULT 95,
  `status` varchar(255) NOT NULL DEFAULT 'warning',
  `image_url` varchar(255) NOT NULL,
  `symptoms` text DEFAULT NULL,
  `organic_remedy` text DEFAULT NULL,
  `chemical_remedy` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('1', NULL, 'Guest Farmer', 'Potato', 'Potato Late Blight', 'Phytophthora infestans', '96.7', 'critical', 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a81?auto=format&fit=crop&w=600&q=80', '\"[\\\"Water-soaked dark lesions on leaf tips\\\",\\\"White cottony fungal growth on undersides\\\",\\\"Rapid leaf collapse\\\"]\"', 'Copper oxychloride 50% WP spray @ 3g/L of water.', 'Cymoxanil 8% + Mancozeb 64% WP @ 1.5g/L.', '2026-07-29 05:05:58', '2026-07-29 05:05:58');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('2', NULL, 'Guest Farmer', 'Tomato (Solanum lycopersicum)', 'Tomato Early Blight', 'Alternaria solani', '98.4', 'warning', 'http://localhost:8000/uploads/scans/leaf_1785301839_5513.jpg', '\"[\\\"Concentric dark brown target spots on leaves\\\",\\\"Yellow halo around affected tissue\\\",\\\"Defoliation of lower leaves\\\"]\"', 'Neem oil spray (0.5%) or copper octanoate fungicide every 7 days. Prune bottom infected foliage.', 'Mancozeb 75% WP @ 2g/L of water.', '2026-07-29 05:10:39', '2026-07-29 05:10:39');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('3', NULL, 'Guest Farmer', 'Tomato (Solanum lycopersicum)', 'Tomato Early Blight', 'Alternaria solani', '98.4', 'warning', 'http://localhost:8000/uploads/scans/leaf_1785301839_5513.jpg', '\"[\\\"Concentric dark brown target spots on leaves\\\",\\\"Yellow halo around affected tissue\\\",\\\"Defoliation of lower leaves\\\"]\"', 'Neem oil spray (0.5%) or copper octanoate fungicide every 7 days. Prune bottom infected foliage.', 'Mancozeb 75% WP @ 2g/L of water.', '2026-07-29 05:10:45', '2026-07-29 05:10:45');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('4', NULL, 'Guest Farmer', 'Rice / Paddy (Oryza sativa)', 'Rice Leaf Blast', 'Magnaporthe oryzae', '95.2', 'critical', 'http://localhost:8000/uploads/scans/leaf_1785302114_7522.jpg', '\"[\\\"Spindle-shaped or diamond-shaped leaf lesions with gray\\\\\\/white centers\\\",\\\"Reddish-brown margins around leaf spots\\\",\\\"Node rotting and collar leaf damage\\\"]\"', 'Spray Pseudomonas fluorescens bio-fungicide @ 10g/L or Neem cake extract (5%).', 'Tricyclazole 75% WP @ 0.6g/L or Isoprothiolane 40% EC @ 1.5ml/L of water.', '2026-07-29 05:15:15', '2026-07-29 05:15:15');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('5', NULL, 'Guest Farmer', 'Rice / Paddy (Oryza sativa)', 'Rice Leaf Blast', 'Magnaporthe oryzae', '95.2', 'critical', 'http://localhost:8000/uploads/scans/leaf_1785302114_7522.jpg', '\"[\\\"Spindle-shaped or diamond-shaped leaf lesions with gray\\\\\\/white centers\\\",\\\"Reddish-brown margins around leaf spots\\\",\\\"Node rotting and collar leaf damage\\\"]\"', 'Spray Pseudomonas fluorescens bio-fungicide @ 10g/L or Neem cake extract (5%).', 'Tricyclazole 75% WP @ 0.6g/L or Isoprothiolane 40% EC @ 1.5ml/L of water.', '2026-07-29 05:15:25', '2026-07-29 05:15:25');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('6', NULL, 'Guest Farmer', 'Maize / Corn (Zea mays)', 'Corn Common Rust', 'Puccinia sorghi', '97.4', 'warning', 'http://localhost:8000/uploads/scans/leaf_1785302288_9573.jpg', '\"[\\\"Oval to elongate cinnamon-brown pustules on upper\\\\\\/lower leaf surfaces\\\",\\\"Ruptured pustules releasing powdery rust-colored spores\\\",\\\"Chlorosis and leaf tissue scorching around pustule clusters\\\"]\"', 'Apply wettable sulfur formulations @ 3.0g/L at first appearance of rust pustules.', 'Propiconazole 25% EC @ 1.0ml/L or Azoxystrobin 23% SC @ 1.0ml/L of water.', '2026-07-29 05:18:09', '2026-07-29 05:18:09');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('7', NULL, 'Guest Farmer', 'Tomato (Solanum lycopersicum)', 'Tomato Early Blight', 'Alternaria solani', '97.4', 'warning', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80', '\"[\\\"Concentric dark brown target-board leaf spots\\\",\\\"Yellow chlorotic halo surrounding leaf lesions\\\",\\\"Lower leaf wilting and early leaf drop\\\"]\"', 'Apply 0.5% Neem Oil spray or Copper Octanoate fungicide every 7 days. Remove infected lower leaves.', 'Mancozeb 75% WP @ 2.0g/Liter or Chlorothalonil 75% WP @ 2.0g/Liter of water.', '2026-07-29 05:18:21', '2026-07-29 05:18:21');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('8', NULL, 'Guest Farmer', 'Crop Foliage (Wheat / Paddy / Tomato / Potato)', 'Healthy Foliage', 'Pathogen-Free Organically Active Tissue', '98.4', 'healthy', 'http://localhost:8000/uploads/scans/leaf_1785302309_5331.jpg', '\"[\\\"Vibrant green uniform leaf pigmentation\\\",\\\"Intact venation without necrosis or chlorosis\\\",\\\"High chlorophyll density & active photosynthesis\\\"]\"', 'Maintain regular bio-fertilizer schedule (Azotobacter & Phosphobacteria).', 'No chemical fungicide required. Continue standard plant nutrition.', '2026-07-29 05:18:30', '2026-07-29 05:18:30');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('9', NULL, 'Guest Farmer', 'Rice / Paddy (Oryza sativa)', 'Rice Leaf Blast', 'Magnaporthe oryzae', '95', 'critical', 'http://localhost:8000/uploads/scans/leaf_1785302720_7922.jpg', '\"[\\\"Spindle-shaped or diamond-shaped leaf lesions with gray\\\\\\/white centers\\\",\\\"Reddish-brown margins around leaf spots\\\",\\\"Node rotting and collar leaf damage\\\"]\"', 'Spray Pseudomonas fluorescens bio-fungicide @ 10g/L or Neem cake extract (5%).', 'Tricyclazole 75% WP @ 0.6g/L or Isoprothiolane 40% EC @ 1.5ml/L of water.', '2026-07-29 05:25:21', '2026-07-29 05:25:21');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('10', NULL, 'Guest Farmer', 'Tomato (Solanum lycopersicum)', 'Tomato Early Blight', 'Alternaria solani', '94.8', 'warning', 'http://localhost:8000/uploads/scans/leaf_1785302734_6481.jpg', '\"[\\\"Concentric dark brown target-board leaf spots\\\",\\\"Yellow chlorotic halos expanding around leaf lesions\\\",\\\"Lower leaf wilting and premature defoliation\\\"]\"', 'Apply 0.5% Cold-pressed Neem Oil or Copper Octanoate fungicide every 7-10 days. Remove infected lower leaves.', 'Mancozeb 75% WP @ 2.0g/Liter or Chlorothalonil 75% WP @ 2.0g/Liter of water.', '2026-07-29 05:25:34', '2026-07-29 05:25:34');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('11', NULL, 'Guest Farmer', 'Tomato (Solanum lycopersicum)', 'Tomato Early Blight', 'Alternaria solani', '94.8', 'warning', 'http://localhost:8000/uploads/scans/leaf_1785302858_3908.jpg', '\"[\\\"Concentric dark brown target-board leaf spots\\\",\\\"Yellow chlorotic halos expanding around leaf lesions\\\",\\\"Lower leaf wilting and premature defoliation\\\"]\"', 'Apply 0.5% Cold-pressed Neem Oil or Copper Octanoate fungicide every 7-10 days. Remove infected lower leaves.', 'Mancozeb 75% WP @ 2.0g/Liter or Chlorothalonil 75% WP @ 2.0g/Liter of water.', '2026-07-29 05:27:39', '2026-07-29 05:27:39');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('12', NULL, 'Guest Farmer', 'Document / Non-Plant Object', 'Non-Leaf Image Detected', 'N/A', '99', 'invalid', 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a81?auto=format&fit=crop&w=600&q=80', '\"[\\\"No plant leaf tissue or green\\\\\\/brown foliage detected in the image.\\\"]\"', 'Please upload or capture a clear photo of an actual plant leaf.', 'N/A - Non-plant image.', '2026-07-29 05:28:32', '2026-07-29 05:28:32');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('13', NULL, 'Guest Farmer', 'Maize / Corn (Zea mays)', 'Corn Common Rust', 'Puccinia sorghi', '94.3', 'warning', 'http://localhost:8000/uploads/scans/leaf_1785302960_7335.jpg', '\"[\\\"Oval to elongate cinnamon-brown pustules on upper\\\\\\/lower leaf surfaces\\\",\\\"Ruptured pustules releasing powdery rust-colored spores\\\",\\\"Chlorosis and leaf tissue scorching around pustule clusters\\\"]\"', 'Apply wettable sulfur formulations @ 3.0g/L at first appearance of rust pustules.', 'Propiconazole 25% EC @ 1.0ml/L or Azoxystrobin 23% SC @ 1.0ml/L of water.', '2026-07-29 05:29:21', '2026-07-29 05:29:21');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('14', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://localhost:8000/uploads/scans/leaf_1785303078_3130.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-07-29 05:31:19', '2026-07-29 05:31:19');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('15', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Non-Plant / Low Crop Foliage Signal', '99.2', 'invalid', 'http://localhost:8000/uploads/scans/leaf_1785303086_7369.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Non-Plant \\\\\\/ Low Crop Foliage Signal).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-07-29 05:31:26', '2026-07-29 05:31:26');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('16', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Non-Plant / Low Crop Foliage Signal', '99.2', 'invalid', 'http://localhost:8000/uploads/scans/leaf_1785303093_2922.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Non-Plant \\\\\\/ Low Crop Foliage Signal).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-07-29 05:31:33', '2026-07-29 05:31:33');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('17', NULL, 'Guest Farmer', 'Rice / Paddy (Oryza sativa)', 'Rice Leaf Blast', 'Magnaporthe oryzae', '95', 'critical', 'http://localhost:8000/uploads/scans/leaf_1785303103_4172.jpg', '\"[\\\"Spindle-shaped or diamond-shaped leaf lesions with gray\\\\\\/white centers\\\",\\\"Reddish-brown margins around leaf spots\\\",\\\"Node rotting and collar leaf damage\\\"]\"', 'Spray Pseudomonas fluorescens bio-fungicide @ 10g/L or Neem cake extract (5%).', 'Tricyclazole 75% WP @ 0.6g/L or Isoprothiolane 40% EC @ 1.5ml/L of water.', '2026-07-29 05:31:44', '2026-07-29 05:31:44');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('18', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Night Landscape / Dark Wallpaper Detected', '99.2', 'invalid', 'http://localhost:8000/uploads/scans/leaf_1785303117_3937.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Night Landscape \\\\\\/ Dark Wallpaper Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-07-29 05:31:58', '2026-07-29 05:31:58');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('19', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Non-Plant / Low Crop Foliage Signal', '99.2', 'invalid', 'http://localhost:8000/uploads/scans/leaf_1785303133_9746.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Non-Plant \\\\\\/ Low Crop Foliage Signal).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-07-29 05:32:14', '2026-07-29 05:32:14');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('20', NULL, 'Guest Farmer', 'Crop Foliage (Wheat / Paddy / Tomato / Potato)', 'Healthy Foliage', 'Pathogen-Free Organically Active Tissue', '98.6', 'healthy', 'http://localhost:8000/uploads/scans/leaf_1785303142_3885.jpg', '\"[\\\"Vibrant green uniform leaf pigmentation\\\",\\\"Intact venation without necrosis or chlorosis\\\",\\\"High chlorophyll density & active photosynthesis\\\"]\"', 'Maintain regular bio-fertilizer schedule (Azotobacter & Phosphobacteria).', 'No chemical fungicide required. Continue standard plant nutrition.', '2026-07-29 05:32:22', '2026-07-29 05:32:22');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('21', NULL, 'Guest Farmer', 'Crop Foliage (Wheat / Paddy / Tomato / Potato)', 'Healthy Foliage', 'Pathogen-Free Organically Active Tissue', '98.6', 'healthy', 'http://localhost:8000/uploads/scans/leaf_1785303165_7250.jpg', '\"[\\\"Vibrant green uniform leaf pigmentation\\\",\\\"Intact venation without necrosis or chlorosis\\\",\\\"High chlorophyll density & active photosynthesis\\\"]\"', 'Maintain regular bio-fertilizer schedule (Azotobacter & Phosphobacteria).', 'No chemical fungicide required. Continue standard plant nutrition.', '2026-07-29 05:32:46', '2026-07-29 05:32:46');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('22', NULL, 'Guest Farmer', 'Rice / Paddy (Oryza sativa)', 'Rice Leaf Blast', 'Magnaporthe oryzae', '95', 'critical', 'http://localhost:8000/uploads/scans/leaf_1785303177_1134.jpg', '\"[\\\"Spindle-shaped or diamond-shaped leaf lesions with gray\\\\\\/white centers\\\",\\\"Reddish-brown margins around leaf spots\\\",\\\"Node rotting and collar leaf damage\\\"]\"', 'Spray Pseudomonas fluorescens bio-fungicide @ 10g/L or Neem cake extract (5%).', 'Tricyclazole 75% WP @ 0.6g/L or Isoprothiolane 40% EC @ 1.5ml/L of water.', '2026-07-29 05:32:58', '2026-07-29 05:32:58');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('23', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://radiation-collaborative-dictionary-patrick.trycloudflare.com/uploads/scans/leaf_1785394362_4884.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-07-30 06:52:43', '2026-07-30 06:52:43');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('24', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Document / Text Paper Detected', '99.2', 'invalid', 'http://radiation-collaborative-dictionary-patrick.trycloudflare.com/uploads/scans/leaf_1785394393_6946.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Document \\\\\\/ Text Paper Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-07-30 06:53:13', '2026-07-30 06:53:13');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('25', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://radiation-collaborative-dictionary-patrick.trycloudflare.com/uploads/scans/leaf_1785394433_8910.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-07-30 06:53:53', '2026-07-30 06:53:53');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('26', NULL, 'Guest Farmer', 'Rice / Paddy (Oryza sativa)', 'Rice Leaf Blast', 'Magnaporthe oryzae', '95', 'critical', 'http://radiation-collaborative-dictionary-patrick.trycloudflare.com/uploads/scans/leaf_1785394465_6204.jpg', '\"[\\\"Spindle-shaped or diamond-shaped leaf lesions with gray\\\\\\/white centers\\\",\\\"Reddish-brown margins around leaf spots\\\",\\\"Node rotting and collar leaf damage\\\"]\"', 'Spray Pseudomonas fluorescens bio-fungicide @ 10g/L or Neem cake extract (5%).', 'Tricyclazole 75% WP @ 0.6g/L or Isoprothiolane 40% EC @ 1.5ml/L of water.', '2026-07-30 06:54:26', '2026-07-30 06:54:26');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('27', NULL, 'Guest Farmer', 'Rice / Paddy (Oryza sativa)', 'Rice Leaf Blast', 'Magnaporthe oryzae', '95', 'critical', 'http://radiation-collaborative-dictionary-patrick.trycloudflare.com/uploads/scans/leaf_1785394465_6204.jpg', '\"[\\\"Spindle-shaped or diamond-shaped leaf lesions with gray\\\\\\/white centers\\\",\\\"Reddish-brown margins around leaf spots\\\",\\\"Node rotting and collar leaf damage\\\"]\"', 'Spray Pseudomonas fluorescens bio-fungicide @ 10g/L or Neem cake extract (5%).', 'Tricyclazole 75% WP @ 0.6g/L or Isoprothiolane 40% EC @ 1.5ml/L of water.', '2026-07-30 06:55:56', '2026-07-30 06:55:56');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('28', NULL, 'Guest Farmer', 'Maize / Corn (Zea mays)', 'Corn Common Rust', 'Puccinia sorghi', '94.3', 'warning', 'http://radiation-collaborative-dictionary-patrick.trycloudflare.com/uploads/scans/leaf_1785395193_7493.jpg', '\"[\\\"Oval to elongate cinnamon-brown pustules on upper\\\\\\/lower leaf surfaces\\\",\\\"Ruptured pustules releasing powdery rust-colored spores\\\",\\\"Chlorosis and leaf tissue scorching around pustule clusters\\\"]\"', 'Apply wettable sulfur formulations @ 3.0g/L at first appearance of rust pustules.', 'Propiconazole 25% EC @ 1.0ml/L or Azoxystrobin 23% SC @ 1.0ml/L of water.', '2026-07-30 07:06:34', '2026-07-30 07:06:34');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('29', NULL, 'Guest Farmer', 'Wheat', 'Healthy Wheat Leaf', 'Triticum aestivum', '97.1', 'healthy', 'http://radiation-collaborative-dictionary-patrick.trycloudflare.com/uploads/scans/leaf_1785395355_9164.jpg', '\"[\\\"Vibrant deep green foliage with uniform leaf tissue\\\",\\\"No spots, pustules, or discoloration detected\\\",\\\"Optimal chlorophyll density\\\"]\"', 'Maintain regular balanced irrigation and bio-fertilizer schedule (Azotobacter & PSB).', 'No chemical fungicides needed. Continue standard crop care.', '2026-07-30 07:09:16', '2026-07-30 07:09:16');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('30', NULL, 'Guest Farmer', 'Wheat', 'Healthy Wheat Leaf', 'Triticum aestivum', '97.1', 'healthy', 'http://radiation-collaborative-dictionary-patrick.trycloudflare.com/uploads/scans/leaf_1785395360_5370.jpg', '\"[\\\"Vibrant deep green foliage with uniform leaf tissue\\\",\\\"No spots, pustules, or discoloration detected\\\",\\\"Optimal chlorophyll density\\\"]\"', 'Maintain regular balanced irrigation and bio-fertilizer schedule (Azotobacter & PSB).', 'No chemical fungicides needed. Continue standard crop care.', '2026-07-30 07:09:21', '2026-07-30 07:09:21');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('31', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Non-Plant / Low Crop Foliage Signal', '99.2', 'invalid', 'http://radiation-collaborative-dictionary-patrick.trycloudflare.com/uploads/scans/leaf_1785395642_1338.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Non-Plant \\\\\\/ Low Crop Foliage Signal).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-07-30 07:14:03', '2026-07-30 07:14:03');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('32', NULL, 'Guest Farmer', 'Tomato (Solanum lycopersicum)', 'Tomato Early Blight', 'Alternaria solani', '96.4', 'warning', 'http://radiation-collaborative-dictionary-patrick.trycloudflare.com/uploads/scans/leaf_1785395656_7786.jpg', '\"[\\\"Concentric dark brown rings forming target-shaped spots\\\",\\\"Yellow halos surrounding leaf lesions\\\",\\\"Premature defoliation starting from lower leaves\\\"]\"', 'Apply neem oil (0.5%) or copper octanoate fungicide every 7 days. Remove and destroy infected lower leaves.', 'Mancozeb 75% WP @ 2g/L or Chlorothalonil 75% WP @ 2g/L of water.', '2026-07-30 07:14:17', '2026-07-30 07:14:17');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('33', NULL, 'Guest Farmer', 'Document / Non-Plant Object', 'Non-Leaf Image Detected', 'N/A', '99', 'invalid', 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a81?auto=format&fit=crop&w=600&q=80', '\"[\\\"No plant leaf tissue or green\\\\\\/brown foliage detected in the image.\\\"]\"', 'Please upload or capture a clear photo of an actual plant leaf.', 'N/A - Non-plant image.', '2026-07-30 11:54:23', '2026-07-30 11:54:23');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('34', NULL, 'Guest Farmer', 'Document / Non-Plant Object', 'Non-Leaf Image Detected', 'N/A', '99', 'invalid', 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a81?auto=format&fit=crop&w=600&q=80', '\"[\\\"No plant leaf tissue or green\\\\\\/brown foliage detected in the image.\\\"]\"', 'Please upload or capture a clear photo of an actual plant leaf.', 'N/A - Non-plant image.', '2026-07-30 11:56:26', '2026-07-30 11:56:26');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('35', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://col-mortgages-amsterdam-colleague.trycloudflare.com/uploads/scans/leaf_1785412606_8332.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-07-30 11:56:48', '2026-07-30 11:56:48');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('36', NULL, 'Guest Farmer', 'Document / Non-Plant Object', 'Non-Leaf Image Detected', 'N/A', '99', 'invalid', 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a81?auto=format&fit=crop&w=600&q=80', '\"[\\\"No plant leaf tissue or green\\\\\\/brown foliage detected in the image.\\\"]\"', 'Please upload or capture a clear photo of an actual plant leaf.', 'N/A - Non-plant image.', '2026-07-30 12:04:02', '2026-07-30 12:04:02');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('37', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Night Landscape / Dark Wallpaper Detected', '99.2', 'invalid', 'http://192.168.1.64:8000/uploads/scans/leaf_1785471734_4941.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Night Landscape \\\\\\/ Dark Wallpaper Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-07-31 04:22:15', '2026-07-31 04:22:15');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('38', NULL, 'Guest Farmer', 'Rice / Paddy (Oryza sativa)', 'Rice Leaf Blast', 'Magnaporthe oryzae', '95', 'critical', 'http://192.168.1.64:8000/uploads/scans/leaf_1785471745_7335.jpg', '\"[\\\"Spindle-shaped or diamond-shaped leaf lesions with gray\\\\\\/white centers\\\",\\\"Reddish-brown margins around leaf spots\\\",\\\"Node rotting and collar leaf damage\\\"]\"', 'Spray Pseudomonas fluorescens bio-fungicide @ 10g/L or Neem cake extract (5%).', 'Tricyclazole 75% WP @ 0.6g/L or Isoprothiolane 40% EC @ 1.5ml/L of water.', '2026-07-31 04:22:26', '2026-07-31 04:22:26');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('39', NULL, 'Guest Farmer', 'Document / Non-Plant Object', 'Non-Leaf Image Detected', 'N/A', '99', 'invalid', 'https://images.unsplash.com/photo-1592417817098-8f3d6ef23a81?auto=format&fit=crop&w=600&q=80', '\"[\\\"No plant leaf tissue or green\\\\\\/brown foliage detected in the image.\\\"]\"', 'Please upload or capture a clear photo of an actual plant leaf.', 'N/A - Non-plant image.', '2026-08-20 14:10:24', '2026-08-20 14:10:24');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('40', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235060_2034.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:03', '2026-08-20 14:11:03');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('41', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235063_4992.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:04', '2026-08-20 14:11:04');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('42', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235064_5920.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:05', '2026-08-20 14:11:05');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('43', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235065_8926.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:06', '2026-08-20 14:11:06');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('44', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235066_9758.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:07', '2026-08-20 14:11:07');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('45', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235067_5296.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:08', '2026-08-20 14:11:08');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('46', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235068_4120.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:09', '2026-08-20 14:11:09');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('47', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235069_5846.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:10', '2026-08-20 14:11:10');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('48', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235070_6892.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:11', '2026-08-20 14:11:11');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('49', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235071_1626.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:11', '2026-08-20 14:11:11');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('50', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235072_3357.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:12', '2026-08-20 14:11:12');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('51', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235073_5993.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:13', '2026-08-20 14:11:13');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('52', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235074_2725.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:14', '2026-08-20 14:11:14');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('53', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235075_5701.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:15', '2026-08-20 14:11:15');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('54', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235075_7125.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:16', '2026-08-20 14:11:16');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('55', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235076_3379.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:17', '2026-08-20 14:11:17');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('56', NULL, 'Guest Farmer', 'Crop Foliage', 'Healthy Foliage', 'Plant Tissue', '97.5', 'healthy', 'http://10.123.143.94:8000/uploads/scans/leaf_1787235077_6934.jpg', '\"[\\\"Healthy plant leaf tissue detected with optimal chlorophyll levels.\\\"]\"', 'Maintain standard balanced irrigation and bio-fertilizer care (Azotobacter & PSB).', 'No chemical fungicide required. Continue standard plant care.', '2026-08-20 14:11:18', '2026-08-20 14:11:18');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('57', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:20:02', '2026-08-20 14:20:02');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('58', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:21:03', '2026-08-20 14:21:03');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('59', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:22:04', '2026-08-20 14:22:04');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('60', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:23:04', '2026-08-20 14:23:04');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('61', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:24:05', '2026-08-20 14:24:05');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('62', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:25:05', '2026-08-20 14:25:05');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('63', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:26:06', '2026-08-20 14:26:06');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('64', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:27:07', '2026-08-20 14:27:07');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('65', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:27:20', '2026-08-20 14:27:20');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('66', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:27:25', '2026-08-20 14:27:25');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('67', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://robin-must-wider-wagon.trycloudflare.com/uploads/scans/leaf_1787235602_3448.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:28:26', '2026-08-20 14:28:26');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('68', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://10.123.143.94:8000/uploads/scans/leaf_1787236331_5520.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:32:12', '2026-08-20 14:32:12');
INSERT INTO `scans` (`id`, `user_id`, `user_name`, `crop`, `disease_name`, `scientific_name`, `confidence`, `status`, `image_url`, `symptoms`, `organic_remedy`, `chemical_remedy`, `created_at`, `updated_at`) VALUES ('69', NULL, 'Guest Farmer', 'Non-Plant / Scenic Object', 'Non-Leaf Image Detected', 'Scenic Landscape / Mountain Sky Detected', '99.2', 'invalid', 'http://10.123.143.94:8000/uploads/scans/leaf_1787236331_5520.jpg', '\"[\\\"The uploaded photo was identified as a non-plant image (Scenic Landscape \\\\\\/ Mountain Sky Detected).\\\",\\\"No crop foliage or agricultural leaf tissue signals were detected.\\\"]\"', 'Please upload or capture a clear close-up photo of an actual plant/crop leaf.', 'N/A - Non-plant image.', '2026-08-20 14:33:12', '2026-08-20 14:33:12');

DROP TABLE IF EXISTS `sessions`;
CREATE TABLE `sessions` (
  `id` varchar(255) NOT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `payload` longtext NOT NULL,
  `last_activity` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sessions_user_id_index` (`user_id`),
  KEY `sessions_last_activity_index` (`last_activity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `sessions` (`id`, `user_id`, `ip_address`, `user_agent`, `payload`, `last_activity`) VALUES ('6kF1Te8ruRayBXh0kYoTS032P6xnPYkfd6p7IgmO', NULL, '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36 Edg/150.0.0.0', 'YTozOntzOjY6Il90b2tlbiI7czo0MDoieFB3d254bVgwR3BRYXQwenF1ZFdmZE9XR2tmR1NCN3NSNFNZeWFjSyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMCI7czo1OiJyb3V0ZSI7Tjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', '1785471094');
INSERT INTO `sessions` (`id`, `user_id`, `ip_address`, `user_agent`, `payload`, `last_activity`) VALUES ('aqkulcehcj8SgH2xjbhUPdQGO4gkxwSZabIuIYEQ', NULL, '127.0.0.1', 'curl/8.21.0', 'YTozOntzOjY6Il90b2tlbiI7czo0MDoiMjZzVHAyNllDY3BRMnFZYXZPMXhHY1ZldGc4bEtYcUViTkYxbFVwWCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMCI7czo1OiJyb3V0ZSI7Tjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', '1785470940');

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `username` varchar(255) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `role` varchar(255) NOT NULL DEFAULT 'Farmer',
  `google_id` varchar(255) DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('1', 'Apurv', NULL, 'apurv@agribandhu.in', 'Crop Farmer', NULL, NULL, NULL, '$2y$12$keDEQfY0zZSM/BuFVOCSEekcdHLkKGXjCCpcYYh4YQagmGsq1KAM6', NULL, '2026-07-29 05:02:15', '2026-07-29 05:02:15');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('2', 'newapurv', NULL, 'apurvgoel68@gmail.com', 'Gardener', NULL, NULL, NULL, '$2y$12$aWwDOp9w9fO/ZkbN0OO4Su76Jj0y1nK/a6jQpPhqiqR6zjFlmOkT.', NULL, '2026-07-29 05:03:49', '2026-07-29 05:03:49');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('3', 'Mobile App Farmer', NULL, 'farmer_mobile@agri.com', 'Farmer', NULL, NULL, NULL, '$2y$12$4pWRXGNlIGUNhqMhOEsVJOMPuICl7MNwbEi8A97ae6HC7XGMdnjN2', NULL, '2026-07-29 07:57:51', '2026-07-29 07:57:51');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('4', 'PhpMyAdmin Sync Farmer', NULL, 'phpmyadmin_user@agri.com', 'Farmer', NULL, NULL, NULL, '$2y$12$EeDv1ZQ4hG3XEXnfFtvGouw1CYCjpgpx2GN4KacH8UDUKWVvBlhD.', NULL, '2026-07-30 05:15:35', '2026-07-30 05:15:35');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('5', 'Ramesh Kumar', NULL, 'ramesh@agribandhu.in', 'Farmer', NULL, NULL, NULL, '$2y$12$aJ9aaMoN.SZPo6dYSdrjVuggH2szy7nGP2/Y/hHpw03ZEHFNO7.Pe', NULL, '2026-07-30 05:23:27', '2026-07-30 05:23:27');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('6', 'nubasur', NULL, 'nubasur@agribandhu.in', 'Farmer', NULL, NULL, NULL, '$2y$12$rvDE5J1Dv9FEgDxgcY.bjOr4I2LYv7FLBNnvDE/2jAljkwWohJYYS', NULL, '2026-07-30 06:29:22', '2026-07-30 06:29:22');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('7', 'nubasur', NULL, 'nubasur@123456', 'Farmer', NULL, NULL, NULL, '$2y$12$RQoybX/iHQRPhUhHw0KwfuAishYpQ.ZGeDkJJHPFsbX6gOllHQmpG', NULL, '2026-07-30 06:41:25', '2026-07-30 06:41:25');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('8', 'Nubasur', NULL, 'nubasur@12345', 'Farmer', NULL, NULL, NULL, '$2y$12$LE1O2WyH.r3a8XGQAek52e7WPXTepsTYEm0nmaDnmKHbV82qSvqL.', NULL, '2026-07-30 06:51:53', '2026-07-30 06:51:53');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('9', 'Majoro project', NULL, 'major@123456', 'Student', NULL, NULL, NULL, '$2y$12$J.9Dl9l3lMaYCxX8LvQdX.cG6nOyBF7I2DPuINsQTXs8bOxTPqz3i', NULL, '2026-07-30 06:56:47', '2026-07-30 06:56:47');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('10', 'Ajju', NULL, 'arjun@gmail.com', 'Gardener', NULL, NULL, NULL, '$2y$12$ViLydIPI3wLAfLlZK5xZyeiwq0mhEBPAX.JyG4ypnT6lzBybDB1fO', NULL, '2026-07-30 07:04:34', '2026-07-30 07:04:34');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('11', 'Olivia Das', NULL, 'dasolivia54@gmail.com', 'Farmer', NULL, NULL, NULL, '$2y$12$VUWb8mzLyqVmB7FH4t/g2ObYl0IVnnBqEfzOLTVV9B79O0rGuVNsC', NULL, '2026-07-30 07:06:07', '2026-07-30 07:06:07');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('12', 'Newuser', NULL, 'new@123456', 'Farmer', NULL, NULL, NULL, '$2y$12$E5R.Gf9OaPXtEHe3M7KDsei2WGiWACSigJVrcEPYYt21N5J9T6vpK', NULL, '2026-07-30 07:13:33', '2026-07-30 07:13:33');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('13', 'Gulu gulu', NULL, 'guchipiku@gmail.com', 'Gardener', NULL, NULL, NULL, '$2y$12$CclKL79piCmV5MgD3Ds5IO4QWbsuQLposcEP1fZD.cshuI/MBP6zu', NULL, '2026-07-30 07:26:14', '2026-07-30 07:26:14');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('15', 'Iajajajja', NULL, 'usjwus@ejsjs', 'Farmer', NULL, NULL, NULL, '$2y$12$gkjZ9MIxaxje09z8d9NMdu7Cih9BQSPZ.atRoAc1QwKQV0a.bOZI2', NULL, '2026-07-30 07:28:35', '2026-07-30 07:28:35');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('16', 'Test Farmer', NULL, 'test_farmer@agribandhu.in', 'Farmer', NULL, NULL, NULL, '$2y$12$SD0NydiWF7ZMvOMryuOVVOQegrFZOV9zlGoNnr/mJ0tvxYTaZURg2', NULL, '2026-07-30 08:57:31', '2026-07-30 08:57:31');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('17', 'After ui ux', NULL, 'ui123456@gmail.com', 'Farmer', NULL, NULL, NULL, '$2y$12$146sXQWcFwPR.zVkd9X0p.WS/33B4SRFMRhohuWf97y4oPTmnTKV6', NULL, '2026-07-30 09:17:08', '2026-07-30 09:17:08');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('18', 'Direct Register Test', NULL, 'direct_register@agribandhu.in', 'Farmer', NULL, NULL, NULL, '$2y$12$Rcak0kze.MQXF4pqVGTvSOHZ9s.28oKXmAyXc.7ll8XGrLKhWmbSu', NULL, '2026-07-30 10:44:21', '2026-07-30 10:44:21');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('19', 'Direct Register Test 2', NULL, 'direct_register2@agribandhu.in', 'Farmer', NULL, NULL, NULL, '$2y$12$eHY6hiGkDjq2Qc7S/mAsnecLSPv1TLtw9M2CnYCdw1HxRMFZHFDLm', NULL, '2026-07-30 10:44:23', '2026-07-30 10:44:23');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('20', 'Ushsusus', NULL, 'ushaujss@gmail.com', 'Farmer', NULL, NULL, NULL, '$2y$12$9b6T5WFb3dVj/RIIF.GyuuycIB8w/IN1erTu13EI8VUqlPexU49n6', NULL, '2026-07-30 10:46:50', '2026-07-30 10:46:50');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('21', 'Live Check', NULL, 'live_check@agribandhu.in', 'Farmer', NULL, NULL, NULL, '$2y$12$vw9.VO7kfHVRjBVdvw0tdOktM6uw4gjzuXBXd/Ib8cfHiZRYNi9w6', NULL, '2026-07-30 11:47:28', '2026-07-30 11:47:28');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('22', 'Isisiwj', NULL, 'apurvgoe8@gmail.com', 'Farmer', NULL, NULL, NULL, '$2y$12$ro8qGDfbwzCW1R5HZrI73.C5wqO1/8rtR.4B6bxP/ZAHgFaTYzQEW', NULL, '2026-07-30 11:56:04', '2026-07-30 11:56:04');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('23', 'Kanchan', NULL, 'kanchandangwal01@gmail.com', 'Gardener', NULL, NULL, NULL, '$2y$12$yiMXNO7lArrshbBuSXfuGePxM9lQKe.blTIqEwprRRkAvnBNz1QRy', NULL, '2026-07-30 12:02:27', '2026-07-30 12:02:27');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('24', 'Apurv', NULL, 'aourvgoel68@gmail.com', 'Agronomist', NULL, NULL, NULL, '$2y$12$GFnCTJDN42YC7J0fhHSIp.jID4XU8Mtqc7XLc23y7NhN0lhtBTJ3.', NULL, '2026-08-20 14:00:17', '2026-08-20 14:00:17');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('25', 'Ramesh', NULL, 'ramesh@gmail.com', 'Farmer', NULL, NULL, NULL, '$2y$12$V8b77jT/l2hSsU.soRCST.F9myJj0WHazlrenGYRbvo3qeAvw4CIG', NULL, '2026-08-20 14:13:59', '2026-08-20 14:13:59');
INSERT INTO `users` (`id`, `name`, `username`, `email`, `role`, `google_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES ('26', 'Ramesh2. 0', NULL, 'apurv68@gmail.com', 'Farmer', NULL, NULL, NULL, '$2y$12$VsL4efoAaq/jroMzWiR3We7b0DHhKB/Y5rGgpa6KMPN.L.GoSBvtu', NULL, '2026-08-20 14:32:06', '2026-08-20 14:32:06');

SET FOREIGN_KEY_CHECKS=1;
